"""add_subjects

Revision ID: 09c08eefe833
Revises: 95dde10e2b19
Create Date: 2026-04-21 21:47:25.959294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c08eefe833'
down_revision: Union[str, Sequence[str], None] = '95dde10e2b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subjects', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subjects')
    # ### end Alembic commands ###
